name: Build and Test Package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: yarn
      - run: yarn test
      - run: yarn build
